language: ruby
cache: bundler
rvm:
- 1.9.3
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- source setEnvVariables
- rake db:migrate
env:
  global:
  - secure: cGOZZ/Hxj/nHC39ubaV7yjGLAbGIVCTGL3dd6vErLwOEPdovP1YdBgJ2PwYT/qXgIUChwg78/t0t6KLV+a8kHyfBT7MH1k1qBX6IYeSkqHLOfU3GoB9Tg2GjaTck5FLeBe25lR1kI1wwUl4KN7fKtCkcLHtaTZd2Hy8R3B0CaGs=
  - secure: NDh39uevHgQqxWrbFu1J7gRAvdp5dMfxbfPDmRMrtL8AKLQygcBZmsmYgr6Azr/wVl2MFY8Yg3eRDxrqosAU023Y6k+VXmLmGtBlvp7iF6V6zG3PiuUtPfwSBTF2UdQL6eQeRIQmo/DWTZs3vXZIoD/BIOTgiZTKxfaGWs9A5ng=
