#!/bin/sh

sudo yum update 
sudo yum install postgresql postgresql-server postgresql-devel postgresql-contrib postgresql-docs 
sudo service postgresql initdb 

# Sets up c9 environment for dev/test

sudo chmod 644 /var/lib/pgsql9/data/pg_hba.conf
sudo service postgresql start
sudo sudo -u postgres psql < init_c9.sql

# Install utilities
gem install travis
#why does this take so long every time and what does it do?
#npm install phantomjs

# Set ENV variables
source ./setEnvVariables
bin/rails db:environment:set RAILS_ENV=development

# Setup DB'
rake db:reset
rake db:migrate
rake db:seed


# Alternative DB import from prod (https://devcenter.heroku.com/articles/heroku-postgres-import-export#import-to-heroku-postgres)
# pg_restore --verbose --clean --no-acl --no-owner -h localhost -U postgres -d gpucc b001.dump