#!/bin/sh

# Sets up c9 environment for dev/test

sudo chmod 644 /etc/postgresql/9.3/main/pg_hba.conf
sudo service postgresql start
sudo sudo -u postgres psql < init_c9.sql

# Set ENV variables
./setEnvVariables

# Setup DB
rake db:migrate
rake db:seed
