#!/bin/sh

# Set ENV variables
export SECRET_TOKEN=`rake secret`
export APPNAME=FitStalker
export ADMIN_EMAIL=heisler@epimp.com
export ADMIN_NAME=Hamish Eisler
#export ADMIN_PASSWORD=
export GMAIL_USERNAME=gpucctester@gmail.com
#export GMAIL_PASSWORD=
export ROLES='[admin, user, trainer, VIP]'